import { NestFactory } from "@nestjs/core";
import { AppModule, listenAndConfigureApp } from "./app.module";
import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";
import { readFile, writeFile } from "fs/promises";
import crypto from "crypto";
import os from "os";
import openapiTS, { astToString } from "openapi-typescript";

// Auto generated by the Nest OpenAPI Plugin.
import metadata from "./metadata";
import path from "path";
import { NestExpressApplication } from "@nestjs/platform-express";
import { addValidationErrorsToOpenAPI } from "./postProcessOpenAPI";
import { ValidationErrorOutDTO } from "./contacts/entities/validationError.dto";

const openAPISchemaPath = "./openAPI.json";
const openAPITSSchemaPath = "./src/grassroots-shared/openAPI.gen.ts";

async function bootstrap(port: number): Promise<void> {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);
  await listenAndConfigureApp(app, port);

  const config = new DocumentBuilder()
    .setTitle("Grassroots")
    .setDescription("The Grassroots API description")
    .setVersion("0.0")
    .build();

  await SwaggerModule.loadPluginMetadata(metadata);
  const openAPI = SwaggerModule.createDocument(app, config, {
    autoTagControllers: true,
    extraModels: [ValidationErrorOutDTO],
  });

  addValidationErrorsToOpenAPI(openAPI);

  const openAPIStr = JSON.stringify(openAPI, null, 2);
  const openAPIHash = crypto
    .createHash("sha1")
    .update(openAPIStr)
    .digest("base64");

  const openAPIHashPath = path.join(os.tmpdir(), "nestOpenAPIHash");
  const lastHash = await readFile(openAPIHashPath, "utf8")
    .then((s) => {
      return s;
    })
    .catch(() => null);

  // The OpenAPI Spec has changed, due some post processing.
  if (openAPIHash != lastHash) {
    await writeFile(openAPIHashPath, openAPIHash);
    await writeFile(openAPISchemaPath, openAPIStr);
    console.log("Updating OpenAPI Schema TS bindings");
    const ast = await openapiTS(openAPIStr);
    const contents = astToString(ast);
    await writeFile(openAPITSSchemaPath, contents);
    console.log("Done updating OpenAPI Schema TS bindings");
  } else {
    console.log("Skip updating OpenAPI");
  }
}

const port = process.env.PORT ? parseInt(process.env.PORT) : 3000;
void bootstrap(port);
