packages:
  - grassroots-backend
  - grassroots-backend-tests
  - grassroots-frontend
  - eslint_rules
  - generate-metadata
  - grassroots-shared
  - grassroots-shared-net
  - openapi-paths
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@scarf/scarf"
  - "@swc/core"
  - esbuild
  - unrs-resolver
