packages:
  - grassroots-backend
  - grassroots-frontend
  - eslint_rules
  - grassroots-shared
  - casl-subjects

ignoredBuiltDependencies:
  - esbuild
  - "@nestjs/core"
  - "@scarf/scarf"
  - "@swc/core"
