import { Client } from "openapi-fetch";
import type { paths } from "../src/grassroots-shared/openAPI.gen"; // generated by openapi-typescript
import { NestExpressApplication } from "@nestjs/platform-express";
import { e2eBeforeAll } from "../src/testing/e2eSetup";
import { AppService } from "../src/app.service";
import { AppController } from "../src/app.controller";

describe("AppController (e2e)", () => {
  let app: NestExpressApplication;
  let grassrootsAPI: Client<paths>;

  beforeAll(async () => {
    ({ app, grassrootsAPI } = await e2eBeforeAll({
      providers: [AppService],
      controllers: [AppController],
    }));
  });

  afterAll(async () => {
    await app.close();
  });

  it("/ (GET)", async () => {
    const result = await grassrootsAPI.GET("/");
    expect(result.response.status).toBe(200);
    expect(result.data?.message).toBe("Hello World!");
  });
});
