import { Client } from "openapi-fetch";
import type { paths } from "../src/grassroots-shared/OpenAPI.gen"; // generated by openapi-typescript
import { NestExpressApplication } from "@nestjs/platform-express";
import { e2eBeforeAll } from "../src/testing/E2eSetup";
import { AppService } from "../src/App.service";
import { AppController } from "../src/App.controller";

describe("AppController (e2e)", () => {
  const getFixture = useE2ETestFixture({
    providers: [AppService],
    controllers: [AppController],
  });

  it("/ (GET)", async () => {
    const f = getFixture();

    const result = await f.grassrootsAPI.GET("/");
    expect(result.response.status).toBe(200);
    expect(result.data?.message).toBe("Hello World!");
  });
});
