export enum Permission {
  VIEW_CONTACTS = "VIEW_CONTACTS",
  MANAGE_CONTACTS = "MANAGE_CONTACTS",
  MANAGE_USERS = "MANAGE_USERS",
}

export type PermissionValue =
  | "VIEW_CONTACTS"
  | "MANAGE_CONTACTS"
  | "MANAGE_USERS";
