/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/Users'
import { Route as SharedSearchImport } from './routes/SharedSearch'
import { Route as SearchImport } from './routes/Search'
import { Route as MeImport } from './routes/Me'
import { Route as CreateContactImport } from './routes/CreateContact'
import { Route as IndexImport } from './routes/index'
import { Route as OrganizationsOrganizationIdImport } from './routes/Organizations/$organizationId'

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/Users',
  path: '/Users',
  getParentRoute: () => rootRoute,
} as any)

const SharedSearchRoute = SharedSearchImport.update({
  id: '/SharedSearch',
  path: '/SharedSearch',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/Search',
  path: '/Search',
  getParentRoute: () => rootRoute,
} as any)

const MeRoute = MeImport.update({
  id: '/Me',
  path: '/Me',
  getParentRoute: () => rootRoute,
} as any)

const CreateContactRoute = CreateContactImport.update({
  id: '/CreateContact',
  path: '/CreateContact',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OrganizationsOrganizationIdRoute =
  OrganizationsOrganizationIdImport.update({
    id: '/Organizations/$organizationId',
    path: '/Organizations/$organizationId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/CreateContact': {
      id: '/CreateContact'
      path: '/CreateContact'
      fullPath: '/CreateContact'
      preLoaderRoute: typeof CreateContactImport
      parentRoute: typeof rootRoute
    }
    '/Me': {
      id: '/Me'
      path: '/Me'
      fullPath: '/Me'
      preLoaderRoute: typeof MeImport
      parentRoute: typeof rootRoute
    }
    '/Search': {
      id: '/Search'
      path: '/Search'
      fullPath: '/Search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/SharedSearch': {
      id: '/SharedSearch'
      path: '/SharedSearch'
      fullPath: '/SharedSearch'
      preLoaderRoute: typeof SharedSearchImport
      parentRoute: typeof rootRoute
    }
    '/Users': {
      id: '/Users'
      path: '/Users'
      fullPath: '/Users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/Organizations/$organizationId': {
      id: '/Organizations/$organizationId'
      path: '/Organizations/$organizationId'
      fullPath: '/Organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/CreateContact': typeof CreateContactRoute
  '/Me': typeof MeRoute
  '/Search': typeof SearchRoute
  '/SharedSearch': typeof SharedSearchRoute
  '/Users': typeof UsersRoute
  '/Organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/CreateContact': typeof CreateContactRoute
  '/Me': typeof MeRoute
  '/Search': typeof SearchRoute
  '/SharedSearch': typeof SharedSearchRoute
  '/Users': typeof UsersRoute
  '/Organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/CreateContact': typeof CreateContactRoute
  '/Me': typeof MeRoute
  '/Search': typeof SearchRoute
  '/SharedSearch': typeof SharedSearchRoute
  '/Users': typeof UsersRoute
  '/Organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/CreateContact'
    | '/Me'
    | '/Search'
    | '/SharedSearch'
    | '/Users'
    | '/Organizations/$organizationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/CreateContact'
    | '/Me'
    | '/Search'
    | '/SharedSearch'
    | '/Users'
    | '/Organizations/$organizationId'
  id:
    | '__root__'
    | '/'
    | '/CreateContact'
    | '/Me'
    | '/Search'
    | '/SharedSearch'
    | '/Users'
    | '/Organizations/$organizationId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateContactRoute: typeof CreateContactRoute
  MeRoute: typeof MeRoute
  SearchRoute: typeof SearchRoute
  SharedSearchRoute: typeof SharedSearchRoute
  UsersRoute: typeof UsersRoute
  OrganizationsOrganizationIdRoute: typeof OrganizationsOrganizationIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateContactRoute: CreateContactRoute,
  MeRoute: MeRoute,
  SearchRoute: SearchRoute,
  SharedSearchRoute: SharedSearchRoute,
  UsersRoute: UsersRoute,
  OrganizationsOrganizationIdRoute: OrganizationsOrganizationIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/CreateContact",
        "/Me",
        "/Search",
        "/SharedSearch",
        "/Users",
        "/Organizations/$organizationId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/CreateContact": {
      "filePath": "CreateContact.tsx"
    },
    "/Me": {
      "filePath": "Me.tsx"
    },
    "/Search": {
      "filePath": "Search.tsx"
    },
    "/SharedSearch": {
      "filePath": "SharedSearch.tsx"
    },
    "/Users": {
      "filePath": "Users.tsx"
    },
    "/Organizations/$organizationId": {
      "filePath": "Organizations/$organizationId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
