graph TD
	QHZT("eslint_rules#build") --> ETTT("___ROOT___")
	JEGP("grassroots-backend#build") --> EMLE("grassroots-backend#gen-files-only")
	JEGP("grassroots-backend#build") --> LRHC("grassroots-shared#build")
	EMLE("grassroots-backend#gen-files-only") --> GLAO("grassroots-backend#gen-metadata")
	EMLE("grassroots-backend#gen-files-only") --> LRHC("grassroots-shared#build")
	GLAO("grassroots-backend#gen-metadata") --> LRHC("grassroots-shared#build")
	VELR("grassroots-backend-e2etests#build") --> JEGP("grassroots-backend#build")
	VELR("grassroots-backend-e2etests#build") --> LRHC("grassroots-shared#build")
	VELR("grassroots-backend-e2etests#build") --> TXWC("grassroots-shared-net#build")
	VELR("grassroots-backend-e2etests#build") --> WCIN("openapi-paths#build")
	TPBW("grassroots-frontend#build") --> LRHC("grassroots-shared#build")
	TPBW("grassroots-frontend#build") --> TXWC("grassroots-shared-net#build")
	TPBW("grassroots-frontend#build") --> WCIN("openapi-paths#build")
	LRHC("grassroots-shared#build") --> ETTT("___ROOT___")
	TXWC("grassroots-shared-net#build") --> LRHC("grassroots-shared#build")
	TXWC("grassroots-shared-net#build") --> WCIN("openapi-paths#build")
	WCIN("openapi-paths#build") --> EMLE("grassroots-backend#gen-files-only")
