graph TD
	QHZT("eslint_rules#build") --> ETTT("___ROOT___")
	JEGP("generate-metadata#build") --> ETTT("___ROOT___")
	EMLE("generate-metadata#gen-metadata") --> ETTT("___ROOT___")
	LRHC("grassroots-backend#build") --> GLAO("grassroots-shared#build")
	LRHC("grassroots-backend#build") --> VELR("grassroots-shared#tsc")
	TXWC("grassroots-backend#gen-files-only") --> GLAO("grassroots-shared#build")
	TXWC("grassroots-backend#gen-files-only") --> VELR("grassroots-shared#tsc")
	WCIN("grassroots-backend#tsc") --> VELR("grassroots-shared#tsc")
	TPBW("grassroots-backend-e2etests#build") --> LRHC("grassroots-backend#build")
	TPBW("grassroots-backend-e2etests#build") --> WCIN("grassroots-backend#tsc")
	TPBW("grassroots-backend-e2etests#build") --> GLAO("grassroots-shared#build")
	TPBW("grassroots-backend-e2etests#build") --> VELR("grassroots-shared#tsc")
	TPBW("grassroots-backend-e2etests#build") --> BHWE("grassroots-shared-net#build")
	TPBW("grassroots-backend-e2etests#build") --> MKNG("grassroots-shared-net#tsc")
	TPBW("grassroots-backend-e2etests#build") --> IRKD("openapi-paths#build")
	TPBW("grassroots-backend-e2etests#build") --> UWBQ("openapi-paths#tsc")
	FBWM("grassroots-frontend#build") --> GLAO("grassroots-shared#build")
	FBWM("grassroots-frontend#build") --> VELR("grassroots-shared#tsc")
	FBWM("grassroots-frontend#build") --> BHWE("grassroots-shared-net#build")
	FBWM("grassroots-frontend#build") --> MKNG("grassroots-shared-net#tsc")
	FBWM("grassroots-frontend#build") --> IRKD("openapi-paths#build")
	FBWM("grassroots-frontend#build") --> UWBQ("openapi-paths#tsc")
	GLAO("grassroots-shared#build") --> EMLE("generate-metadata#gen-metadata")
	VELR("grassroots-shared#tsc") --> EMLE("generate-metadata#gen-metadata")
	BHWE("grassroots-shared-net#build") --> GLAO("grassroots-shared#build")
	BHWE("grassroots-shared-net#build") --> VELR("grassroots-shared#tsc")
	BHWE("grassroots-shared-net#build") --> IRKD("openapi-paths#build")
	BHWE("grassroots-shared-net#build") --> UWBQ("openapi-paths#tsc")
	MKNG("grassroots-shared-net#tsc") --> VELR("grassroots-shared#tsc")
	MKNG("grassroots-shared-net#tsc") --> UWBQ("openapi-paths#tsc")
	IRKD("openapi-paths#build") --> TXWC("grassroots-backend#gen-files-only")
	UWBQ("openapi-paths#tsc") --> TXWC("grassroots-backend#gen-files-only")
