name: "CI"

on:
  pull_request:

jobs:
  nodejs-checks:
    name: Lint, Build, Format and Auto-Commit changes
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE: "Modified files from CI"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
          token: ${{ secrets.ACTION_PAT }}

      - name: Check for workflow loop using commit messages
        run: |
          CURRENT_COMMIT_MESSAGE=$(git show -s --pretty=%B HEAD)
          LAST_COMMIT_MESSAGE=$(git show -s --pretty=%B HEAD~1)

          if [ "$CURRENT_COMMIT_MESSAGE" == "$COMMIT_MESSAGE" ] && \
            [ "$LAST_COMMIT_MESSAGE" == "$COMMIT_MESSAGE" ]; then
            echo "It looks like the last two commits are from CI. This indicates a loop."
            exit 1
          fi

      - name: Setup Node.js & pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run syncpack
        run: |
          pnpm exec syncpack fix-mismatches
          pnpm install

      - name: "Services: Start Test Services"
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "./docker/compose-ci.yaml"

      - name: Build everything
        run: pnpm run -r build

      - name: Migrate DB
        run: cd grassroots-backend && pnpm run db-up

      - name: Setup tbls
        uses: k1low/setup-tbls@v1

      - name: Run tbls to generate database document
        run: tbls doc --rm-dist

      - name: Run ESLint
        run: pnpm exec eslint . --output-file eslint_report.json --format json --fix
        continue-on-error: true

      - name: Format code with Prettier
        run: pnpm exec prettier --write .

      - name: Push Changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ env.COMMIT_MESSAGE }}
          commit_options: "--no-verify"

      - name: Fail workflow if files were modified
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: |
          echo "There were modified files after running CI."
          exit 1

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@3.0.0

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONS: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run tstyche
        run: cd grassroots-backend && pnpm run test:tstyche

      - name: Check mikro-orm migration
        run: |
          if ! cd grassroots-backend && pnpm run db-check 2>&1 | grep -q "No changes required, schema is up-to-date"; then
            exit 1
          fi

      - name: "Services: Start Test Services"
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "./docker/compose-ci.yaml"

      - name: Tests
        run: cd grassroots-backend && pnpm run test:ci
