name: "CI"

on:
  pull_request:

jobs:
  nodejs-checks:
    name: Node.js check
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE: "Modified files from CI"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
          token: ${{ secrets.ACTION_PAT }}

      - name: Setup Repo
        uses: ./.github/actions/setup-repo

      - name: Check for workflow loop using commit messages
        run: |
          CURRENT_COMMIT_MESSAGE=$(git show -s --pretty=%B HEAD)
          LAST_COMMIT_MESSAGE=$(git show -s --pretty=%B HEAD~1)

          if [ "$CURRENT_COMMIT_MESSAGE" == "$COMMIT_MESSAGE" ] && \
             [ "$LAST_COMMIT_MESSAGE" == "$COMMIT_MESSAGE" ]; then
            echo "It looks like the last two commits are from CI. This indicates a loop."
            exit 1
          fi

      - name: Run syncpack
        run: |
          npx syncpack fix-mismatches
          npm install
          npm install --prefix grassroots-frontend
          npm install --prefix grassroots-backend

      - name: Run ESLint
        run: npx eslint . --output-file eslint_report.json --format json --fix
        continue-on-error: true

      - name: Format code with Prettier
        run: npx prettier --write .

      - name: Push Changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ env.COMMIT_MESSAGE }}
          commit_options: "--no-verify"

      - name: Fail workflow if files were modified
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: |
          echo "There were modified files after running CI."
          exit 1

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@3.0.0

  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Repo
        uses: ./.github/actions/setup-repo

      - name: Run ESLint
        run: npx eslint .

  typecript:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Repo
        uses: ./.github/actions/setup-repo

      - name: Run TypeScript Check
        run: |
          npx tsc --noEmit --project grassroots-frontend
          npx tsc --noEmit --project grassroots-backend
